document.addEventListener('DOMContentLoaded', () => {
    const cursos = [
    //cursos tecnólogos area de tecnologia
    { name: "Análise e Desenvolvimento de Sistemas", area: "Tecnologia", type: "Tecnólogo" }, 
    //cursos de bacharelado de Saúde
    { name: "Nutrição", area: "Saúde", type: "Bacharelado" },
    //cursos de Educação
    { name: "Pedagogia", area: "Educação", type: "Licenciatura"},
    //cursos de bacharelado 
    { name: "Administração", area: "Administração", type: "Bacharelado" },
      // cursos de pós graduação em saúde
      {"name":"Gerontologia 520h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Gerontologia e saúde mental 520h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Antropologia 750h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Acupuntura 720h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Acupuntura 750h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Analises Clínicas 720h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Analises Clínicas e Microbiologia 520h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Análises clínicas e microbiologia 750h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Análises clínicas 750h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Anatomia e Patologia Associada 720h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Anatomia e patologia associada. 750h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Anatomia Funcional 720h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Anatomia funcional 750h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Assistência de Enfermagem Domiciliar 720h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Assistência de enfermagem domiciliar 750h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Assistência de Enfermagem Familiar 720h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Assistência de Enfermagem Familiar 750h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Assistência Social e Saúde Pública 720h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Assuntos Regulatórios na indústria Farmacêutica 720h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Atenção de emergência pré-hospitalar 720h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Atenção de emergência pré-hospitalar 750h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Atenção Farmacêutica 720h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Atendimento de Emergência pré- hospitalar 720h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Atividade Física e Bem Estar 520h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Atividade física e bem-estar 750h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Atividade Física e Saúde 520h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Atividade física e saúde 750h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Atividade Física para grupos Especiais  720h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Atividade física para grupos especiais 750h","area":"Saúde","type":"Pós-graduação"},
      {"name":"Analises Clínicas 720h","area":"Saude","type":"Pós-graduação"},
      {"name":"Analises Clínicas e Microbiologia 520h","area":"Saude","type":"Pós-graduação"},
      {"name":"Análises clínicas e microbiologia 750h","area":"Saude","type":"Pós-graduação"},
    {"name":"Análises clínicas 750h","area":"Saude","type":"Pós-graduação"},
    {"name":"Anatomia e Patologia Associada 720h","area":"Saude","type":"Pós-graduação"},
    {"name":"Anatomia e patologia associada 750h","area":"Saude","type":"Pós-graduação"},
    {"name":"Anatomia Funcional 720h","area":"Saude","type":"Pós-graduação"},
    {"name":"Anatomia funcional 750h","area":"Saude","type":"Pós-graduação"},
    {"name":"Auditoria em Enfermagem: 620h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Auditoria em sistemas de Saúde: 720h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Autismo: 1000h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Avaliação Educacional: 720h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Avaliação Física","area":"Saúde","type":"Pós-graduação"},
    {"name":"Ortopédica","area":"Saúde","type":"Pós-graduação"},
    {"name":"Esportiva e Funcional: 720h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Avaliação física","area":"Saúde","type":"Pós-graduação"},
    {"name":"Ortopédica","area":"Saúde","type":"Pós-graduação"},
    {"name":"Esportiva e Funcional: 750h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Controle de Infecção Hospitalar: 720h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Controle de Infecção Hospitalar: 750h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Cuidador de Apoio de Alunos com Deficiência nas Escolas: 720h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Cuidados Paliativos: 750h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Cuidados Paliativos e Terapia da Dor: 720h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Cuidados paliativos e terapia da dor: 750h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Cuidados paliativos: 750h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Deficiência Visual e Tecnologia Assistida: 740h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Deficiência Visual e Tecnologia Assistiva: 740h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Deficiência intelectual: 750h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Deficiências intelectuais e múltiplas: 680h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Deficiências Intelectuais e Múltiplas: 1000h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Deficiências múltiplas e intelectuais: 1000h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Deficiências Múltiplas e Intelectuais: 680h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Deficiências múltiplas e sensoriais: 1000h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Deficiências sensoriais e múltiplas: 640h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Dependência Química: 420h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Dependência química e qualidade de vida: 620h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Dependência química e qualidade de vida: 750h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Dependência química: 750h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Dependência Tóxica: 420h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Dependência Tóxica e Qualidade de Vida: 620h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Docência em enfermagem: 620h","area":"Saúde","type":"Pós-graduação"},
    {"name":"Cosmetologia","area":"Saúde","type":"Pós-graduação","hours":"Avançada 720"},
    {"name":"Cosmetologia","area":"Saúde","type":"Pós-graduação","hours":"Avançada 750"},
    {"name":"Cuidados Paliativos:","area":"Saúde","type":"Pós-graduação","hours":"750h"},
    {"name":"Cuidados Paliativos e Terapia da Dor:","area":"Saúde","type":"Pós-graduação","hours":"720h"},
    {"name":"Cuidados paliativos e terapia da dor:","area":"Saúde","type":"Pós-graduação","hours":"750h"},
    {"name":"Cuidados paliativos:","area":"Saúde","type":"Pós-graduação","hours":"750h"},
    {"name":"Deficiência Visual e Tecnologia Assistida:","area":"Saúde","type":"Pós-graduação","hours":"740h"},
    {"name":"Deficiência Visual e Tecnologia Assistiva:","area":"Saúde","type":"Pós-graduação","hours":"740h"},
    {"name":"Deficiência intelectual:","area":"Saúde","type":"Pós-graduação","hours":"750h"},
    {"name":"Deficiências intelectuais e múltiplas:","area":"Saúde","type":"Pós-graduação","hours":"680h"},
    {"name":"Deficiências Intelectuais e Múltiplas.:","area":"Saúde","type":"Pós-graduação","hours":"1000h"},
    {"name":"Deficiências múltiplas e intelectuais:","area":"Saúde","type":"Pós-graduação","hours":"1000h"},
    {"name":"Deficiências Múltiplas e Intelectuais.:","area":"Saúde","type":"Pós-graduação","hours":"680h"},
    {"name":"Deficiências múltiplas e sensoriais:","area":"Saúde","type":"Pós-graduação","hours":"1000h"},
    {"name":"Deficiências sensoriais e múltiplas:","area":"Saúde","type":"Pós-graduação","hours":"640h"},
    {"name":"Dependência Química:","area":"Saúde","type":"Pós-graduação","hours":"420h"},
    {"name":"Dependência química e qualidade de vida:","area":"Saúde","type":"Pós-graduação","hours":"620h"},
    {"name":"Dependência química e qualidade de vida:","area":"Saúde","type":"Pós-graduação","hours":"750h"},
    {"name":"Dependência química:","area":"Saúde","type":"Pós-graduação","hours":"750h"},
    {"name":"Dependência Tóxica:","area":"Saúde","type":"Pós-graduação","hours":"420h"},
    {"name":"Dependência Tóxica e Qualidade de Vida:","area":"Saúde","type":"Pós-graduação","hours":"620h"},
    {"name":"Docência em enfermagem:","area":"Saúde","type":"Pós-graduação","hours":"620h"},
  
    {"name":"Educação em tempo integral:","area":"Saúde","type":"Pós-graduação","hours":"660h"},
    {"name":"Farmácia Clínica -520h","area":"Saúde","type":"Pós-graduação"},
  {"name":"Farmácia clínica com atenção farmacêutica -620h","area":"Saúde","type":"Pós-graduação"},
  {"name":"Farmácia Clínica Direcionada à Prescrição Farmacêutica -720h","area":"Saúde","type":"Pós-graduação"},
  {"name":"Farmácia clínica direcionada a prescrição farmacêutica -750h","area":"Saúde","type":"Pós-graduação"},
  {"name":"Farmácia clínica e hospitalar -750h","area":"Saúde","type":"Pós-graduação"},
  {"name":"Farmácia Clínica Hospitalar -720h","area":"Saúde","type":"Pós-graduação"},
  {"name":"Farmácia Hospitalar -720h","area":"Saúde","type":"Pós-graduação"},
  {"name":"Farmácia Oncológica -740h","area":"Saúde","type":"Pós-graduação"},
  {"name":"Farmacologia -520h","area":"Saúde","type":"Pós-graduação"},
  {"name":"Farmacologia Clínica -520h","area":"Saúde","type":"Pós-graduação"},
  {"name":"Farmacologia clínica -750h","area":"Saúde","type":"Pós-graduação"},
  {"name":"Farmacologia e Terapêutica -740h","area":"Saúde","type":"Pós-graduação"},
  {"name":"Farmacologia e Terapêutica Veterinária -740h","area":"Saúde","type":"Pós-graduação"},
  {"name":"Farmacologia -750h","area":"Saúde","type":"Pós-graduação"},
  {"name":"Farmacoterapia Estética -720h","area":"Saúde","type":"Pós-graduação"},
  {"name":"Farmacoterapia Estética -750h","area":"Saúde","type":"Pós-graduação"},
  {"name":"Fitoterapia -740h","area":"Saúde","type":"Pós-graduação"},
  {"name":"Fitoterapia -750h","area":"Saúde","type":"Pós-graduação"},
  {"name":"Epidemiologia e vigilância em saúde -750h","area":"Saúde","type":"Pós-graduação"},
  
    //Pós- graduação em Psicologia
    {"name":"Gênero e Sexualidade 720h","area":"Psicologia","type":"Pós-graduação"},
    {"name":"Gênero e sexualidade 750h","area":"Psicologia","type":"Pós-graduação"},
    {"name":"Aconselhamento e Psicologia Pastoral 720h","area":"Psicologia","type":"Pós-graduação"},
    {"name":"Aconselhamento e psicologia pastoral 750h","area":"Psicologia","type":"Pós-graduação"},
    {"name":"Distúrbio da fala e da linguagem:750h","area":"Psicologia","type":"Pós-graduação","hours":"750h"},
    {"name":"Distúrbio da fala e da linguagem:740h","area":"Psicologia","type":"Pós-graduação","hours":"740h"},
    //Pós- graduação em Gastronomia
    {"name":"Gastronomia Contemporânea 720h","area":"Gastronomia","type":"Pós-graduação"},
    {"name":"Gastronomia Funcional e Natural 720h","area":"Gastronomia","type":"Pós-graduação"},
    {"name":"Gastronomia Vegetariana 720h","area":"Gastronomia","type":"Pós-graduação"},
  
    //Pós- graduação em Eportes
    {"name":"Futebol de Campo e Futsal: Da Categoria de Base a profissional 720h","area":"Esportes","type":"Pós-graduação"},
    //Pós- graduação direito
    {"name":"Advocacia Empresarial 750h","area":"Direito","type":"Pós-graduação"},
     {"name":"Assistência Sóciojurídica e Segurança pública 750h","area":"Direito","type":"Pós-graduação"},
    {"name":"Ciências Criminais: 720h","area":"Direito","type":"Pós-graduação"},
    {"name":"Criminologia: 720h","area":"Direito","type":"Pós-graduação"},
    {"name":"Direito eletrônico:","area":"Direito","type":"Pós-graduação","hours":"720h"},
    {"name":"Direito educacional e gestão escolar:","area":"Direito","type":"Pós-graduação","hours":"620h"},
    {"name":"Direito empresarial:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direito Administrativo:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direito Ambiental:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direito Ambiental Empresarial:","area":"Direito","type":"Pós-graduação","hours":"400h"},
    {"name":"Direito Aplicado aos Serviços da Saúde:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direito Civil:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direito militar:","area":"Direito","type":"Pós-graduação","hours":"720h"},
    {"name":"Direito constitucional:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direito da criança, dos idosos e juventude:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direito da juventude, criança e idosos:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direito da previdência social:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direito de família:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direito de processo civil:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direito desportivo:","area":"Direito","type":"Pós-graduação","hours":"720h"},
    {"name":"Direito do consumidor:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direito do Desporto:","area":"Direito","type":"Pós-graduação","hours":"720h"},
    {"name":"Direito do trabalho:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direito educacional:","area":"Direito","type":"Pós-graduação","hours":"720h"},
    {"name":"Direito eleitoral:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direito imobiliário:","area":"Direito","type":"Pós-graduação","hours":"720h"},
    {"name":"Direito notarial e registral:","area":"Direito","type":"Pós-graduação","hours":"620h"},
    {"name":"Direito penal:","area":"Direito","type":"Pós-graduação","hours":"720h"},
    {"name":"Direito penal e processo penal:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direito penal e processual penal:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direito previdenciário:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direito processual civil:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direito público:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direito Público com Ênfase em Contratos e Licitações:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direito trabalhista:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direito tributário:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direitos humanos e questões étnico-sociais:","area":"Direito","type":"Pós-graduação","hours":"720h"},
    {"name":"Direitos humanos e ressocialização:","area":"Direito","type":"Pós-graduação","hours":"750h"},
    {"name":"Direitos humanos na escola:","area":"Direito","type":"Pós-graduação","hours":"520h"},
    {"name":"Direitos Humanos, Responsabilidade Social e Cidadania Global:","area":"Direito","type":"Pós-graduação","hours":"720h"},
    {"name":"Direitos sociais e competências profissionais do assistente social:","area":"Direito","type":"Pós-graduação","hours":"720h"},
    {"name":"Educação no Sistema Penitenciário","area":"Direito","type":"Pós-graduação","hours":"750h"},
     //Pós- graduação Agronomia
     {"name":"Agricultura de Precisão 740h","area":"Agronomia","type":"Pós-graduação"},
     {"name":"Agricultura Orgânica 720h","area":"Agronomia","type":"Pós-graduação"},
     {"name":"Agronegócio 750h","area":"Agronomia","type":"Pós-graduação"},
     {"name":"Agronomia  720h","area":"Agronomia","type":"Pós-graduação"},
    {"name":"Cafeicultura: 720h","area":"Agronomia","type":"Pós-graduação"},
    {"name":"Café: 720h","area":"Agronomia","type":"Pós-graduação"},
    {"name":"Fertilidade/ Manejo de Solos e Nutrição de Plantas -720h","area":"Agronomia","type":"Pós-graduação"},
    {"name":"Fertilização de Solos -620h","area":"Agronomia","type":"Pós-graduação"},
  
     //Pós- graduação em tecnologia
     {"name":"Engenharia de Software:720h","area":"Tecnologia","type":"Pós-graduação"},
      //Pós graduação Artes
      {"name":"Arte : Educação : 720h","area":"Artes","type":"Pós-graduação"},
      {"name":"Arte na educação: Dança","area":"Artes","type":"Pós-graduação"},
      {"name":"música e teatro : 620h","area":"Artes","type":"Pós-graduação"},
      {"name":"Artes : 420h","area":"Artes","type":"Pós-graduação"},
      {"name":"Artes e Educação : 720h","area":"Artes","type":"Pós-graduação"},
      {"name":"Artes Visuais : 630h","area":"Artes","type":"Pós-graduação"},
      {"name":"Arteterapia : 750h","area":"Artes","type":"Pós-graduação"},
      {"name":"Comunicação Alternativa e Tecnologia Assistiva: 1000h","area":"Artes","type":"Pós-graduação"},
      { "name":"Educação artística : 750h","area":"Educação","type":"Pós-graduação"},
      {"name":"Ensino da Educação Física e Artes:620h","area":"Artes","type":"Pós-graduação"},
      {"name":"Ensino de Artes:420h","area":"Artes","type":"Pós-graduação"},
      {"name":"Ensino de Artes- Técnicas e Procedimentos -720h","area":"Artes","type":"Pós-graduação"},
      {"name":"Ensino de Educação Física e Artes -620h","area":"Artes","type":"Pós-graduação"},
      {"name":"Ensino Religioso e Artes -620h","area":"Artes","type":"Pós-graduação"},
    //Pós- graduação em Administração
    {"name":"Formação em coaching 520h","area":"Administração","type":"Pós-graduação"},
    {"name":"Geomarketing e Inteligência de Mercado 720h","area":"Administração","type":"Pós-graduação"},
    {"name":"Gerenciamento de projetos no setor público 720h","area":"Administração","type":"Pós-graduação"},
    {"name":"Gerenciamentos de concessionárias de veículos 720h","area":"Administração","type":"Pós-graduação"},
    {"name":"Gerenciamento de projetos 420h","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração aplicada e gestão empresarial 620h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração de Casas Legislativas 750h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração de Condomínios","area":"Administração","type":"Pós-graduação","hours":"720h"},
    {"name":"Administração de Conflitos e Gestão Empresarial 620h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração de Projetos 420h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração de Recursos Humanos no Setor Público (Rh) 720h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração do Setor Público 520h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração do SUAS - Sistema Único de Assistência Social 620h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração e Auditoria em Serviços de Saúde 420h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração e Recursos Humanos (Rh) 620h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração em Marketing de Serviços e Social 620h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração Estratégica 420h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração Estratégica de Marketing 620h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração Estratégica em Finanças 620h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração financeira 720h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração Hospitalar 420h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração Hospitalar e Gestão da Produção 620h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração Hospitalar e Gestão de Pessoas 620h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração Hospitalar e Gestão Pública 620h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração Hospitalar e Marketing 620h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração Hospitalar e Recursos Humanos (Rh) 620h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração para engenheiros720h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração Patrimonial em Organizações Públicas 720h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração Pública 520h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração Pública e Finanças 620h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração Pública e Gestão Ambiental 620h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração Pública e Gestão de Pessoas 620h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração Pública e Gestão Estratégica 620h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração Pública e Marketing 620h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Administração Pública e Recursos Humanos (Rh)620h ","area":"Administração","type":"Pós-graduação"},
    {"name":"Educação e Segurança no Trânsito 520h ","area":"Administração","type":"Pós-graduação"},
     {"name":"Administração: Auditoria e Controladoria: 750h","area":"Administração","type":"Pós-graduação"},
     {"name":"Auditoria e Gestão da Comunicação e Informação: 720h","area":"Administração","type":"Pós-graduação"},
     {"name":"Auditoria e Perícia Ambiental: 750h","area":"Administração","type":"Pós-graduação"},
     {"name":"Auditoria e Perícia Contábil: 720h","area":"Administração","type":"Pós-graduação"},
     {"name":"Auditoria em Organizações do Setor Público: 720h","area":"Administração","type":"Pós-graduação"},
     {"name":"Auditoria em Sistemas de Saúde: 720h","area":"Administração","type":"Pós-graduação"},
     {"name":"Auditoria Empresarial: 720h","area":"Administração","type":"Pós-graduação"},
     {"name":"Auditoria Hospitalar: 720h","area":"Administração","type":"Pós-graduação"},
     {"name":"Coaching: 520h","area":"Administração","type":"Pós-graduação"},
     {"name":"Coaching Educacional: 720h","area":"Administração","type":"Pós-graduação"},
     {"name":"Comércio Exterior: 620h","area":"Administração","type":"Pós-graduação"},
     {"name":"Compliance: 740h","area":"Administração","type":"Pós-graduação"},
     {"name":"Departamento Pessoal: 720h","area":"Administração","type":"Pós-graduação"},
     {"name":"Educação corporativa: 750h","area":"Administração","type":"Pós-graduação"},
     {"name":"Departamento Pessoal 720h:","area":"Administração","type":"Pós-graduação","hours":"720h"},
     {"name":"Educação corporativa 750h:","area":"Administração","type":"Pós-graduação","hours":"750h"},
     {"name":"Finanças 420h","area":"Administração","type":"Pós-graduação"},
     {"name":"Finanças Aplicadas a Gestão em RH 750h","area":"Administração","type":"Pós-graduação"},
     {"name":"Finanças Corporativas -420h","area":"Administração","type":"Pós-graduação"},
     {"name":"Finanças Corporativas e Estatística 620h","area":"Administração","type":"Pós-graduação"},
     {"name":"Finanças Corporativas e Gestão Hospitalar 620h","area":"Administração","type":"Pós-graduação"},
     {"name":"Finanças Corporativas e Matemática 620h","area":"Administração","type":"Pós-graduação"},
     {"name":"Finanças e Estatística 620h","area":"Administração","type":"Pós-graduação"},
     {"name":"Finanças e Gestão Hospitalar 620h","area":"Administração","type":"Pós-graduação"},
     {"name":"Finanças e Matemática 620h","area":"Administração","type":"Pós-graduação"},
  
     //Pós- graduação em Educação
     {"name":"Geografia 420h","area":"Educação","type":"Pós-graduação"},
     {"name":"Geografia do Brasil 720h","area":"Educação","type":"Pós-graduação"},
     {"name":"Geografia e meio ambiente 620h","area":"Educação","type":"Pós-graduação"},
     {"name":"Geografia regional brasileira 720horas","area":"Educação","type":"Pós-graduação"},
     {"name":"Geografia/ história e sustentabilidade 620h","area":"Educação","type":"Pós-graduação"},
     {"name":"Geografia/ meio ambiente e história 620h","area":"Educação","type":"Pós-graduação"},
     {"name":"Geografia/ meio ambiente e sustentabilidade 620h","area":"Educação","type":"Pós-graduação"},
     {"name":"A função do secretário escolar na contemporaneidade 720h ","area":"Educação","type":"Pós-graduação"},
     {"name":"ABA - análise do comportamento aplicada 750h ","area":"Educação","type":"Pós-graduação"},
     {"name":"ABA- Análise do comportamento aplicada 720h ","area":"Educação","type":"Pós-graduação"},
     {"name":"abordagem eduaional por princípiios 750h ","area":"Educação","type":"Pós-graduação"},
     {"name":"Administração do Ambiente Escolar 420h ","area":"Educação","type":"Pós-graduação"},
     {"name":"Administração e inspeção Escolar 620h ","area":"Educação","type":"Pós-graduação"},
     {"name":"Administração e Orientação Escolar 620h ","area":"Educação","type":"Pós-graduação"},
     {"name":"Administração e Supervisão Escolar 620h ","area":"Educação","type":"Pós-graduação"},
     {"name":"Administração Educacional 420h ","area":"Educação","type":"Pós-graduação"},
     {"name":"Administração Escolar 420h ","area":"Educação","type":"Pós-graduação"},
     {"name":"Administração Escolar e inspeção Escolar 620h ","area":"Educação","type":"Pós-graduação"},
     {"name":"Administração Escolar e Orientação Educacional 720h ","area":"Educação","type":"Pós-graduação"},
     {"name":"Administração Escolar e Orientação Escolar 720h ","area":"Educação","type":"Pós-graduação"},
     {"name":"Administração Escolar e Supervisão Escolar 620h ","area":"Educação","type":"Pós-graduação"},
     {"name":"AEE - Atendimento Educacional Especializado 1000h ","area":"Educação","type":"Pós-graduação"},
     {"name":"AEE - Atendimento Educacional Especializado e Educação Inclusiva 1000h ","area":"Educação","type":"Pós-graduação"},
     {"name":"AEE - Atendimento Educacional Especializado e Psicomotricidade 760h ","area":"Educação","type":"Pós-graduação"},
     {"name":"AEE - Atendimento Educacional Especializado e Salas de Recursos Multifuncionais 1000 ","area":"Educação","type":"Pós-graduação"},
     {"name":"AEE- Atendimento educacional especializado 780h ","area":"Educação","type":"Pós-graduação"},
     {"name":"AEE e Educação inclusiva 1000h ","area":"Educação","type":"Pós-graduação"},
     {"name":"AEE e Salas de Recursos Multifuncionais 1000h ","area":"Educação","type":"Pós-graduação"},
     {"name":"Alfabetização e Letramento 420h ","area":"Educação","type":"Pós-graduação"},
     {"name":"Análise do Comportamento 720h ","area":"Educação","type":"Pós-graduação"},
     {"name":"Andragogia e formação de adultos 750h ","area":"Educação","type":"Pós-graduação"},
     {"name":"Contação de História: 720h","area":"Educação","type":"Pós-graduação"},
     {"name":"Biblioteconomia: 520h","area":"Educação","type":"Pós-graduação"},
     {"name":"Biblioteconomia e Gestão de Bibliotecas Escolares: 720h","area":"Educação","type":"Pós-graduação"},
     {"name":"Base Nacional Comum Curricular: Ensino Fundamental: 720h","area":"Educação","type":"Pós-graduação"},
     {"name":"Base Nacional Comum Curricular: Ensino Médio: 720h","area":"Educação","type":"Pós-graduação"},
     {"name":"Bases da Ciência da Saúde e da Ciência Low Carb: 750h","area":"Educação","type":"Pós-graduação"},
     {"name":"Coordenação Escolar: 420h","area":"Educação","type":"Pós-graduação"},
     {"name":"Coordenação Pedagógica: 750h","area":"Educação","type":"Pós-graduação"},
     {"name":"Coordenação Pedagógica e Planejamento: 720h","area":"Educação","type":"Pós-graduação"},
     {"name":"Coordenação Pedagógica e Supervisão Escolar: 720h","area":"Educação","type":"Pós-graduação"},
     {"name":"Coordenador de Projeto em Tempo Integral: 660h","area":"Contabilidade","type":"Pós-graduação"},
     {"name":"Cuidador de Apoio de Alunos com Deficiência nas Escolas: 720h","area":"Educação","type":"Pós-graduação"},
     {"name":"Didática e metodologias ativas de aprendizagem:620h","area":"Educação","type":"Pós-graduação","hours":"620h"},
     {"name":"Educação especial inclusiva com ênfase em gestão:720h","area":"Educação","type":"Pós-graduação","hours":"720h"},
     {"name":"Desenvolvimento o projeto de vida:","area":"Educação","type":"Pós-graduação","hours":"750h"},
     {"name":"Docência da educação infantil e dos anos iniciais: 720h","area":"Educação","type":"Pós-graduação","hours":"720h"},
     {"name":"Docência do Ensino de Gerontologia e Saúde Mental: 720h","area":"Educação","type":"Pós-graduação","hours":"720h"},
     {"name":"Docência do ensino religioso: 720h","area":"Educação","type":"Pós-graduação","hours":"720h"},
     {"name":"Docência do ensino superior e EJA: 620h","area":"Educação","type":"Pós-graduação","hours":"620h"},
     {"name":"Docência do ensino superior: 520h","area":"Educação","type":"Pós-graduação","hours":"520h"},
     {"name":"Docência do ensino superior com ênfase em sistemas de saúde: 720h","area":"Educação","type":"Pós-graduação","hours":"720h"},
     {"name":"Docência do ensino superior da educação física e escolar: 620h","area":"Educação","type":"Pós-graduação","hours":"620h"},
     {"name":"Docência do Ensino Superior de Libras: 720h","area":"Educação","type":"Pós-graduação","hours":"720h"},
     {"name":"Docência do Ensino Superior de Libras –Língua Brasileira de Sinais: 720h","area":"Educação","type":"Pós-graduação","hours":"720h"},
     {"name":"Docência do ensino superior e educação de jovens e adultos: 620h","area":"Educação","type":"Pós-graduação","hours":"620h"},
     {"name":"Docência do ensino superior e educação física: 620h","area":"Educação","type":"Pós-graduação","hours":"620h"},
     {"name":"Docência do ensino superior e inspeção escolar: 720h","area":"Educação","type":"Pós-graduação","hours":"720h"},
     {"name":"Docência do ensino superior e treinamento desportivo: 620h","area":"Educação","type":"Pós-graduação","hours":"620h"},
     {"name":"Docência do ensino superior em administração: 620h","area":"Educação","type":"Pós-graduação","hours":"620h"},
     {"name":"Docência do ensino superior em nutrição: 620h","area":"Educação","type":"Pós-graduação","hours":"620h"},
     {"name":"Docência do ensino teológico: 520h","area":"Educação","type":"Pós-graduação","hours":"520h"},
     {"name":"Docência e Gestão na Educação a Distância: 800h","area":"Educação","type":"Pós-graduação","hours":"800h"},
     {"name":"Docência e Performance na Educação à Distância: 620h","area":"Educação","type":"Pós-graduação","hours":"620h"},
     {"name":"Docência em administração: 720h","area":"Educação","type":"Pós-graduação","hours":"720h"},
     {"name":"Docência em ciências da saúde: 720h","area":"Educação","type":"Pós-graduação","hours":"720h"},
     {"name":"Docência em Engenharia: 720h","area":"Educação","type":"Pós-graduação","hours":"720h"},
     {"name":"Docência em teologia: 520h","area":"Teologia","type":"Pós-graduação","hours":"520h"},
     {"name":"Docência na educação profissional: 620h","area":"Educação","type":"Pós-graduação","hours":"620h"},
     {"name":"Docência no ensino superior e psicomotricidade: 620h","area":"Educação","type":"Pós-graduação","hours":"620h"},
     {"name":"Docência Superior em Gastronomia: 720h","area":"Educação","type":"Pós-graduação","hours":"720h"},
     {"name":"Docência teológica: 520h","area":"Educação","type":"Pós-graduação","hours":"520h"},
     {"name":"Educação a distância: 720h","area":"Educação","type":"Pós-graduação","hours":"720h"},
     {"name":"Educação ambiental: 620h","area":"Educação","type":"Pós-graduação","hours":"620h"},
     {"name":"Educação ambiental e desenvolvimento sustentável: 720h","area":"Educação","type":"Pós-graduação","hours":"720h"},
     {"name":"Educação em direitos humanos: 620h","area":"Educação","type":"Pós-graduação","hours":"620h"},
     {"name":"Diversidade e questões étnico-sociais ou raciais: 620h","area":"Educação","type":"Pós-graduação","hours":"620h"},
     {"name":"Educação em sistemas prisionais: 720h","area":"Educação","type":"Pós-graduação","hours":"720h"},
     {"name":"Educação em tempo integral: 660h","area":"Educação","type":"Pós-graduação","hours":"660h"},
     {"name":"Educação especial: 600h","area":"Educação","type":"Pós-graduação","hours":"600h"},
     {"name":"Educação especial com ênfase em deficiência física: 740h","area":"Educação","type":"Pós-graduação","hours":"740h"},
     {"name":"Educação especial com ênfase em deficiência Intelectual: 750h","area":"Educação","type":"Pós-graduação","hours":"750h"},
     {"name":"Educação especial com ênfase em estimulação precoce: 800h","area":"Educação","type":"Pós-graduação","hours":"800h"},
     {"name":"Educação especial com ênfase em práticas inclusivas: 750h","area":"Educação","type":"Pós-graduação","hours":"750h"},
     {"name":"Educação especial e educação de jovens e adultos: 740h","area":"Educação","type":"Pós-graduação","hours":"740h"},
     {"name":"Educação especial e educação física: 740h","area":"Educação","type":"Pós-graduação","hours":"740h"},
     {"name":"Educação especial e educação física escolar: 740h","area":"Educação","type":"Pós-graduação","hours":"740h"},
     {"name":"Educação especial e educação infantil: 740h","area":"Educação","type":"Pós-graduação","hours":"740h"},
     {"name":"Educação especial e educação pedagógica social: 740h","area":"Educação","type":"Pós-graduação","hours":"740h"},
     {"name":"Educação especial e educação psicomotora: 740h","area":"Educação","type":"Pós-graduação","hours":"740h"},
     {"name":"Educação especial e ensino religioso: 740h","area":"Educação","type":"Pós-graduação","hours":"740h"},
     {"name":"Educação especial e inclusiva: 1000h","area":"Educação","type":"Pós-graduação","hours":"1000h"},
     {"name":"Educação Especial e Inclusiva com Ênfase em Deficiência Intelectual e Múltipla: 750h","area":"Educação","type":"Pós-graduação","hours":"750h"},
     {"name":"Educação especial e inclusiva com ênfase em deficiências: 760h","area":"Educação","type":"Pós-graduação","hours":"760h"},
     {"name":"Educação especial e inclusiva e metodologia de ensino: 700h","area":"Educação","type":"Pós-graduação","hours":"700h"},
     {"name":"Educação especial e inclusiva e neuro psicopedagogia: 840h","area":"Educação","type":"Pós-graduação","hours":"840h"},
     {"name":"Educação especial e inclusiva e neuro psicopedagogia institucional e clínica: 800h","area":"Educação","type":"Pós-graduação","hours":"800h"},
     {"name":"Educação especial e inclusiva- Ênfase na atuação do pedagogo na avaliação diagnóstica: 760h","area":"Educação","type":"Pós-graduação","hours":"760h"},
     {"name":"Educação especial e inclusiva: Ação docente especializada: 760h","area":"Educação","type":"Pós-graduação","hours":"760h"},
     {"name":"Educação especial e informática da educação: 620h","area":"Educação","type":"Pós-graduação","hours":"620h"},
     {"name":"Educação especial e ludo pedagogia: 680h","area":"Educação","type":"Pós-graduação","hours":"680h"},
     {"name":"Educação especial e neuro psicopedagogia: 720h","area":"Educação","type":"Pós-graduação","hours":"720h"},
     {"name":"Educação especial e pedagogia social: 740h","area":"Educação","type":"Pós-graduação","hours":"740h"},
     {"name":"Educação especial e psicomotricidade: 740h","area":"Educação","type":"Pós-graduação","hours":"740h"},
     {"name":"Educação especial e TEA - Transtorno espeto autista: 700h","area":"Educação","type":"Pós-graduação","hours":"700h"},
     {"name":"Educação especial e TGD: 700h","area":"Educação","type":"Pós-graduação","hours":"700h"},
     {"name":"Educação Especial e TGD –Transtornos Globais do Desenvolvimento: 700h","area":"Educação","type":"Pós-graduação","hours":"700h"},
     {"name":"Educação especial e treinamento desportivo: 740h","area":"Educação","type":"Pós-graduação","hours":"740h"},
     {"name":"Educação especial e tutoria: 700h","area":"Educação","type":"Pós-graduação","hours":"700h"},
     {"name":"Educação especial educação pedagógica social: 740h","area":"Educação","type":"Pós-graduação","hours":"740h"},
     {"name":"Educação especial no contexto da neuro pedagogia: 760h","area":"Educação","type":"Pós-graduação","hours":"760h"},
     {"name":"Educação especial/ infantil e TEA: 750h","area":"Educação","type":"Pós-graduação","hours":"750h"},
     {"name":"Educação especial/ infantil e TGD: 700h","area":"Educação","type":"Pós-graduação","hours":"700h"},
     {"name":"Educação Especial/ Infantil e TGD –Transtornos Globais do Desenvolvimento: 700h","area":"Educação","type":"Pós-graduação","hours":"700h"},
     {"name":"Educação infantil:420h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação infantil- Anos inicias e psicopedagogia:760h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação infantil com ênfase em educação especial:740h","area":"Educação","type":"Pós-graduação"},
  {"name":"EDUCAÇÃO INFANTIL COM ÊNFASE EM TEA - TRANSTORNO ESPECTRO AUTISTA:620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação infantil com ênfase em TGD:620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação Infantil com Ênfase em TGD –Transtornos Globais do Desenvolvimento:620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação infantil e alfabetização:720h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação infantil e anos iniciais:420h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação infantil e pedagogia social:620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação Infantil e Psicomotricidade Clínica:720h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação infantil especial e TGD:620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação Infantil: Abordagem Reggio Emília:750h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação infantil: Práticas pedagógicas:720h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação integral:720h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação Musical:740h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação musical e ensino de artes:720h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação no Campo:520h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação profissional e tecnologia:720h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação quilombola:720h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação voltada para o campo:520h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educador no Sistema Penitenciário:750h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educador Social:750h","area":"Educação","type":"Pós-graduação"},
  {"name":"EJA - Educação de Jovens e Adultos e Educação Física Escolar:520h","area":"Educação","type":"Pós-graduação"},
  {"name":"EJA - Educação de Jovens e Adultos e Ensino Religioso:620h","area":"Educação","type":"Pós-graduação"},
  {"name":"EJA - Educação de Jovens e Adultos e Informática da Educação:620h","area":"Educação","type":"Pós-graduação"},
  {"name":"EJA - Educação de Jovens e Adultos e Psicomotricidade:620h","area":"Educação","type":"Pós-graduação"},
  {"name":"EJA e educação física escolar:520h","area":"Educação","type":"Pós-graduação"},
  {"name":"EJA e educação física escolar EJA e ensino religioso:620h","area":"Educação","type":"Pós-graduação"},
  {"name":"EJA e ensino religioso:620h","area":"Educação","type":"Pós-graduação"},
  {"name":"EJA e informática da educação:620h","area":"Educação","type":"Pós-graduação"},
  {"name":"EJA e psicomotricidade:620h","area":"Educação","type":"Pós-graduação"},
  {"name":"EJA- Educação de jovens e adultos:420h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação especial no contexto da neuropedagogia:760h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação especial/ Infantil e TEA:750h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação especial/ infantil e TGD:700h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação Especial/ Infantil e TGD –Transtornos Globais do Desenvolvimento:700h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação especial/ psicopedagogia clínica e institucional:750h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação inclusiva com ênfase em avaliação diagnóstica escolar:760h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação inclusiva e especial:840h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação indígena:750h","area":"Educação","type":"Pós-graduação"},
  {"name":"Educação financeira e neurociência para docentes:720h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Educação Especial Com Ênfase em TEA - TRANSTORNO ESPECTRO AUTISTA -700h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Educação Especial com ênfase em TGD -700h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Educação Especial com Ênfase em TGD - Transtornos Globais do Desenvolvimento -700h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Educação Especial e Ensino Religioso -740h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Educação Especial e Psicomotricidade -740h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Educação Física e Psicomotricidade -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Educação Física e Recreação -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Educação Física e TGD -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Educação Física e TGD – Transtornos Globais do Desenvolvimento -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Educação Física Escolar -420h","area":"Educação","type":"Pós-graduação"},
  {"name":"ENSINO DE EDUCAÇÃO FÍSICA ESCOLAR E TEA - TRANSTORNO ESPECTRO AUTISTA -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Educação Física Escolar na Educação Infantil -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Educação Física na Educação lnfantil -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de EJA -420h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de EJA - Educação 8de Jovens e Adultos -420h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de EJA - Educação de Jovens e Adultos e Ensino Religioso -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de EJA e Ensino Religioso -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de EJA e Psicomotricidade -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Estimulação Precoce -740h","area":"Educação","type":"Pós-graduação"},
  {"name":"Estratégia da Saúde da Família -750h","area":"Educação","type":"Pós-graduação"},
  {"name":"Estratégia da Saúde Familiar - ESF -420h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ética e Responsabilidade Social -720h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ética Profissional -720h","area":"Educação","type":"Pós-graduação"},
  {"name":"Etnologia lndígena -720h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Ciências -720h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Artes- Técnicas e Procedimentos -720h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Educação Física e Artes -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Educação Física e EJA -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Educação Física e EJA - Educação de Jovens e Adultos -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Educação Física e Psicomotricidade -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Educação Física e TGD -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Educação Física e TGD – Transtornos Globais do Desenvolvimento -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Educação Física Escolar - 420h ENSINO DE EDUCAÇÃO FÍSICA ESCOLAR E TEA - TRANSTORNO ESPECTRO AUTISTA -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Educação Física Escolar na Educação Infantil -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Educação Física na Educação lnfantil -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de EJA - Educação de Jovens e Adultos -420h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de EJA - Educação de Jovens e Adultos e Ensino Religioso -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de EJA e Ensino Religioso -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de EJA e Psicomotricidade -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Filosofia -420h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Filosofia e Sociologia -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Geografia -420h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Geografia e Meio Ambiente -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino deGeografia","area":"Educação","type":"Pós-graduação"},
  {"name":"História e Sustentabilidade -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino deGeografia","area":"Educação","type":"Pós-graduação"},
  {"name":"Meio Ambiente e História -620h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de História -420h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Língua Espanhola -420h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Língua Inglesa -500h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Língua lnglesa -420h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Língua Portuguesa -720h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Matemática -420h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Química -520h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Sociologia -420h","area":"Educação","type":"Pós-graduação"},
  {"name":"Estratégia da Saúde da Família -750h","area":"Educação","type":"Pós-graduação"},
  {"name":"Estratégia da Saúde Familiar - ESF -420h","area":"Educação","type":"Pós-graduação"},
  {"name":"Formação de Docentes: Educaçãoinfantil","area":"Educação","type":"Pós-graduação"},
  {"name":"Alfabetização e educação especial -800h","area":"Educação","type":"Pós-graduação"},
  {"name":"Ensino de Biologia 420h","area":"Educação","type":"Pós-graduação"},
  {"name":"Filosofia -720h","area":"Educação","type":"Pós-graduação"},
  {"name":"Filosofia da Religião -750h","area":"Educação","type":"Pós-graduação"},
  {"name":"Filosofia e Autoconhecimento: Uso Pessoal e Profissional -720h","area":"Educação","type":"Pós-graduação"},
  {"name":"Filosofia e Direitos Humanos -720h","area":"Educação","type":"Pós-graduação"},
  
  
  
  
     //Pós- graduação em Arquitetura
     {"name":"Arquitetura da Paisagem 720h ","area":"Arquitetura","type":"Pós-graduação"},
     {"name":"Arquitetura e Cidades 720h ","area":"Arquitetura","type":"Pós-graduação"},
     {"name":"Arquitetura e Design de Interiores 720h ","area":"Arquitetura","type":"Pós-graduação"},
     {"name":"Arquitetura e infraestrutura de T.l 720h ","area":"Arquitetura","type":"Pós-graduação"},
     {"name":"Arquitetura e Patrimônio 720h ","area":"Arquitetura","type":"Pós-graduação"},
     {"name":"Arquitetura Escolar 720h ","area":"Arquitetura","type":"Pós-graduação"},
     {"name":"Arquivologia 720h ","area":"Arquitetura","type":"Pós-graduação"},
     //Pós- graduação em Teologia
     {"name":"Aconselhamento e Psicologia Pastoral 720h ","area":"Teologia","type":"Pós-graduação"},
     {"name":"Aconselhamento e psicologia pastoral 750h ","area":"Teologia","type":"Pós-graduação"},
     {"name":"Ciência da Religião: 530h","area":"Teologia","type":"Pós-graduação"},
     {"name":"Educação cristã: 720h","area":"Teologia","type":"Pós-graduação"},
     {"name":"Educação especial e ensino religioso: 740h","area":"Teologia","type":"Pós-graduação"},
     {"name":"Educação especial e ensino religioso: 740h","area":"Teologia","type":"Pós-graduação"},
     {"name":"Docência do ensino superior em teologia: 520h","area":"Teologia","type":"Pós-graduação"},
     {"name":"Docência em teologia: 520h","area":"Teologia","type":"Pós-graduação"},
     {"name":"Docência teológica: 520h","area":"Teologia","type":"Pós-graduação"},
     {"name":"Ensino Religioso -530h","area":"Teologia","type":"Pós-graduação"},
     {"name":"Ensino de Educação Especial e Ensino Religioso -740h","area":"Teologia","type":"Pós-graduação"},
     {"name":"Ensino de EJA - Educação de Jovens e Adultos e Ensino Religioso -620h","area":"Teologia","type":"Pós-graduação"},
     {"name":"Ensino de EJA e Ensino Religioso -620h","area":"Teologia","type":"Pós-graduação"},
     //Pós- graduação Efermagem
     {"name":"Assistência de Enfermagem Domiciliar 720h ","area":"Enfermagem","type":"Pós-graduação"},
     {"name":"Assistência de enfermagem domiciliar 750h ","area":"Enfermagem","type":"Pós-graduação"},
     {"name":"Assistência de Enfermagem Familiar 720h ","area":"Enfermagem","type":"Pós-graduação"},
     {"name":"Assistência de Enfermagem Familiar 750h ","area":"Enfermagem","type":"Pós-graduação"},
     {"name":"Atenção Farmacêutica 720h ","area":"Enfermagem","type":"Pós-graduação"},
     {"name":"Docência em enfermagem: 620h","area":"Enfermagem","type":"Pós-graduação"},
     {"name":"Educação continuada e permanente em enfermagem: 620h","area":"Enfermagem","type":"Pós-graduação"},
     {"name":"Educação continuada e permanente em enfermagem: 750h","area":"Enfermagem","type":"Pós-graduação"},
     {"name":"Enfermagem e cuidado com idosos:750h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem de urgência e emergência:720h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem de urgência e emergência:750h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem do trabalho:420h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem do trabalho:750h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem e saúde coletiva:520h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem e saúde coletiva:750h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem e saúde da mulher:520h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem e saúde da mulher:750h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em cardiologia e hemodinâmica:750h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em dermatologia:720h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em dermatologia:750h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em Estética:720h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em estética:750h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em Estomaterapia:720h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em estomaterapia:750h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em Geriatria e Gerontologia:720h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em geriatria e gerontologia:750h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em Home Care:720h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em home care:750h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em Nefrologia:720h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em nefrologia:750h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em Neurologia:720h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em Oncologia:720h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em oncologia:750h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em Ortopedia e Traumatologia:720h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em ortopedia e traumatologia:750h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em Pediatria e Neonatologia:720h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em pediatria e neonatologia:750h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em Pediatria e Saúde Mental:720h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em pediatria e saúde mental:750h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em Psiquiatria e Saúde Mental:720h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em psiquiatria e saúde mental:750h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em UTI:620h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em UTI Neonatal e Pediátrica:720h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em UTI neonatal e pediátrica:750h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem em UTI:750h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem no Trabalho:420h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem Oncológica Pediátrica:720h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem oncológica pediátrica:750h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem Voltada ao ldoso:620h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem voltada para saúde da mulher:520h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem voltada para UTI:620h","area":"Enfermagem","type":"Pós-graduação"},
      {"name":"Enfermagem voltada para UTI:750h","area":"Enfermagem","type":"Pós-graduação"},
     //Pós- graduação em biblieteconomia
     {"name":"Biblioteconomia 520h ","area":"Biblioteconomia","type":"Pós-graduação"},
     {"name":"Biblioteconomia e Gestão de Bibliotecas Escolares 720h ","area":"Biblioteconomia","type":"Pós-graduação"},
     //Pós- graduação em Biologia
     {"name":"Biologia 420h", "area":"Biologia", "type":"Pós-graduação"},
      {"name":"Biologia Celular e Molecular 720h", "area":"Biologia", "type":"Pós-graduação"},
      {"name":"Biologia Marinha 620h", "area":"Biologia", "type":"Pós-graduação"},
      {"name":"Biomedicina Estética 720h", "area":"Biologia", "type":"Pós-graduação"},
      {"name":"Biomedicina Estética 750h", "area":"Biologia", "type":"Pós-graduação"},
      {"name":"Biotecnologia 720h", "area":"Biologia", "type":"Pós-graduação"},
     {"name":"Consultoria e Certificação Ambiental: 620h","area":"Biologia ","type":"Pós-graduação"},
     {"name":"Educação ambiental: 620h","area":"Biologia","type":"Pós-graduação"},
     {"name":"Ecologia e desenvolvimento sustentável: 720h","area":"Biologia","type":"Pós-graduação"},
     {"name":"Ecologia e gestão ambiental: 720h","area":"Biologia","type":"Pós-graduação"},
     {"name":"Educação do meio ambiente: 420h","area":"Biologia","type":"Pós-graduação"},
     //Pós- graduação em Contabilidade
     {"name":"Contabilidade das Organizações do Terceiro Setor: 720h","area":"Contabilidade","type":"Pós-graduação"},
     {"name":"Contabilidade de Custos: 720h","area":"Contabilidade","type":"Pós-graduação"},
     {"name":"Contabilidade Pública: 750h","area":"Contabilidade","type":"Pós-graduação"},
     {"name":"Contabilidade Pública e Auditoria: 720h","area":"Contabilidade","type":"Pós-graduação"},
     {"name":"Controladoria: 420h","area":"Contabilidade","type":"Pós-graduação"},
     {"name":"Controladoria e Gestão: 420h","area":"Contabilidade","type":"Pós-graduação"},
     {"name":"Controladoria Empresarial: 720h","area":"Contabilidade","type":"Pós-graduação"},
     {"name":"Coordenador de Projeto em Tempo Integral: 660h","area":"Contabilidade","type":"Pós-graduação"},
     //Pós- graduação Engenharia Civil
      {"name":"Construção Civil: Residenciais/ Industriais e Especiais: 720h","area":"Engenharia civil","type":"Pós-graduação"},
      //Pós- graduação engenharias (diversas)
      {"name":"Engenharia Elétrica com Ênfase em Instalações Residenciais:720h","area":"Engenharias (diversas)","type":"Pós-graduação"},
      {"name":"Engenharia Agronômica – Ambientes Agrícolas e Seus Campos de Atuação:720h","area":"Engenharias (diversas)","type":"Pós-graduação"},
      {"name":"Engenharia da Qualidade:720h","area":"Engenharias (diversas)","type":"Pós-graduação"},
      {"name":"Engenharia de Controle e Automação Industrial:720h","area":"Engenharias (diversas)","type":"Pós-graduação"},
      {"name":"Engenharia de Estruturas de Concreto Armado:720h","area":"Engenharias (diversas)","type":"Pós-graduação"},
      {"name":"Engenharia de Pavimentação Asfáltica:720h","area":"Engenharias (diversas)","type":"Pós-graduação"},
      {"name":"Engenharia de Segurança do Trabalho:880h","area":"Engenharias (diversas)","type":"Pós-graduação"},
      {"name":"Engenharia de Suprimentos:720h","area":"Engenharias (diversas)","type":"Pós-graduação"},
      {"name":"Engenharia de Tráfego:720h","area":"Engenharias (diversas)","type":"Pós-graduação"},
      {"name":"Engenharia e Gerenciamento de Manutenção:720h","area":"Engenharias (diversas)","type":"Pós-graduação"},
      {"name":"Engenharia Elétrica:720h","area":"Engenharias (diversas)","type":"Pós-graduação"},
      {"name":"Engenharia Elétrica com Ênfase em Instalações Industriais:720h","area":"Engenharias (diversas)","type":"Pós-graduação"},
      {"name":"Engenharia Geotécnica:720h","area":"Engenharias (diversas)","type":"Pós-graduação"},
      // Pós-graduação em Veterinária
  
    { name: "Endocrinologia veterinária:740h", area: "Veterinária", type: "Pós-graduação" },
      ];
  
      const areaSelect = document.getElementById('area');
      const tipoSelect = document.getElementById('tipo');
      const nameInput = document.getElementById('name');
      const resultadosDiv = document.getElementById('resultados');
      const pesquisarButton = document.getElementById('pesquisar');
  
      pesquisarButton.addEventListener('click', () => {
        const selectedArea = areaSelect.value;
        const selectedType = tipoSelect.value;
        const searchName = nameInput.value.toLowerCase();
  
        const filteredCursos = cursos.filter(curso => {
          return (
            (selectedArea === "" || curso.area === selectedArea) &&
            (selectedType === "" || curso.type === selectedType) &&
            (searchName === "" || curso.name.toLowerCase().includes(searchName))
          );
        });
  
        resultadosDiv.innerHTML = filteredCursos.length > 0 
          ? filteredCursos.map(curso => `<p>${curso.name} -  ${curso.type}</p>`).join('') 
          : '<p>Nenhum curso encontrado.</p>';
      });
    });